//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_DentalClaimTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApexSiteURL {
            get {
                return ((string)(this["ApexSiteURL"]));
            }
            set {
                this["ApexSiteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUserName {
            get {
                return ((string)(this["LastUserName"]));
            }
            set {
                this["LastUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenedExclusive {
            get {
                return ((bool)(this["OpenedExclusive"]));
            }
            set {
                this["OpenedExclusive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchDefaultClinic {
            get {
                return ((string)(this["SearchDefaultClinic"]));
            }
            set {
                this["SearchDefaultClinic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAdvancedVideo {
            get {
                return ((bool)(this["UseAdvancedVideo"]));
            }
            set {
                this["UseAdvancedVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EclaimsOpenOutputAfterProcess {
            get {
                return ((bool)(this["EclaimsOpenOutputAfterProcess"]));
            }
            set {
                this["EclaimsOpenOutputAfterProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EclaimsViewClaimsX {
            get {
                return ((int)(this["EclaimsViewClaimsX"]));
            }
            set {
                this["EclaimsViewClaimsX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EclaimsViewClaimsY {
            get {
                return ((int)(this["EclaimsViewClaimsY"]));
            }
            set {
                this["EclaimsViewClaimsY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchPrimaryChecked {
            get {
                return ((bool)(this["SearchPrimaryChecked"]));
            }
            set {
                this["SearchPrimaryChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchSecondaryChecked {
            get {
                return ((bool)(this["SearchSecondaryChecked"]));
            }
            set {
                this["SearchSecondaryChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchPredetermChecked {
            get {
                return ((bool)(this["SearchPredetermChecked"]));
            }
            set {
                this["SearchPredetermChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchUnpaidChecked {
            get {
                return ((bool)(this["SearchUnpaidChecked"]));
            }
            set {
                this["SearchUnpaidChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchHideNotReadyChecked {
            get {
                return ((bool)(this["SearchHideNotReadyChecked"]));
            }
            set {
                this["SearchHideNotReadyChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchShowMyClaimsFirstChecked {
            get {
                return ((bool)(this["SearchShowMyClaimsFirstChecked"]));
            }
            set {
                this["SearchShowMyClaimsFirstChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchSentChecked {
            get {
                return ((bool)(this["SearchSentChecked"]));
            }
            set {
                this["SearchSentChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchResentChecked {
            get {
                return ((bool)(this["SearchResentChecked"]));
            }
            set {
                this["SearchResentChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOnHoldChecked {
            get {
                return ((bool)(this["SearchOnHoldChecked"]));
            }
            set {
                this["SearchOnHoldChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchTracerChecked {
            get {
                return ((bool)(this["SearchTracerChecked"]));
            }
            set {
                this["SearchTracerChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchUpdatedChecked {
            get {
                return ((bool)(this["SearchUpdatedChecked"]));
            }
            set {
                this["SearchUpdatedChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchDefaultStatus {
            get {
                return ((string)(this["SearchDefaultStatus"]));
            }
            set {
                this["SearchDefaultStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MultipleClaimClaimsVisible {
            get {
                return ((int)(this["MultipleClaimClaimsVisible"]));
            }
            set {
                this["MultipleClaimClaimsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\NHDG\\config\\apexedi.config")]
        public string ApexEDIConfigLocation {
            get {
                return ((string)(this["ApexEDIConfigLocation"]));
            }
            set {
                this["ApexEDIConfigLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPaymentLineOnSecondary {
            get {
                return ((bool)(this["ShowPaymentLineOnSecondary"]));
            }
            set {
                this["ShowPaymentLineOnSecondary"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int PaymentStatusID {
            get {
                return ((int)(this["PaymentStatusID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SystemUserID {
            get {
                return ((int)(this["SystemUserID"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal SearchFormsMaxResults {
            get {
                return ((decimal)(this["SearchFormsMaxResults"]));
            }
            set {
                this["SearchFormsMaxResults"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6-6-16")]
        public string LastUpdate {
            get {
                return ((string)(this["LastUpdate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal ProcessClaimsFormMaxResults {
            get {
                return ((decimal)(this["ProcessClaimsFormMaxResults"]));
            }
            set {
                this["ProcessClaimsFormMaxResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any PC")]
        public string LocalComputerName {
            get {
                return ((string)(this["LocalComputerName"]));
            }
            set {
                this["LocalComputerName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x2a\\sqlexpress")]
        public string ServerNameSQL {
            get {
                return ((string)(this["ServerNameSQL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04255")]
        public string GradStudentGroupNum {
            get {
                return ((string)(this["GradStudentGroupNum"]));
            }
            set {
                this["GradStudentGroupNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("claim_production")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
    }
}
