//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_DentalClaimTracker.DCOPlus.Operations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DCOPlus.Operations.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name Key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        C_DentalClaimTracker.DCOPlus.Operations.UploadFileResponse UploadFile(C_DentalClaimTracker.DCOPlus.Operations.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name CBOId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadContent", ReplyAction="*")]
        C_DentalClaimTracker.DCOPlus.Operations.UploadContentResponse UploadContent(C_DentalClaimTracker.DCOPlus.Operations.UploadContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public C_DentalClaimTracker.DCOPlus.Operations.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(C_DentalClaimTracker.DCOPlus.Operations.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Content;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(string Key, string Name, byte[] Content) {
            this.Key = Key;
            this.Name = Name;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public C_DentalClaimTracker.DCOPlus.Operations.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(C_DentalClaimTracker.DCOPlus.Operations.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(bool UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadContent", Namespace="http://tempuri.org/", Order=0)]
        public C_DentalClaimTracker.DCOPlus.Operations.UploadContentRequestBody Body;
        
        public UploadContentRequest() {
        }
        
        public UploadContentRequest(C_DentalClaimTracker.DCOPlus.Operations.UploadContentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadContentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CBOId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Content;
        
        public UploadContentRequestBody() {
        }
        
        public UploadContentRequestBody(string CBOId, string UserName, string Password, string FileName, string Content) {
            this.CBOId = CBOId;
            this.UserName = UserName;
            this.Password = Password;
            this.FileName = FileName;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadContentResponse", Namespace="http://tempuri.org/", Order=0)]
        public C_DentalClaimTracker.DCOPlus.Operations.UploadContentResponseBody Body;
        
        public UploadContentResponse() {
        }
        
        public UploadContentResponse(C_DentalClaimTracker.DCOPlus.Operations.UploadContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadContentResult;
        
        public UploadContentResponseBody() {
        }
        
        public UploadContentResponseBody(bool UploadContentResult) {
            this.UploadContentResult = UploadContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : C_DentalClaimTracker.DCOPlus.Operations.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<C_DentalClaimTracker.DCOPlus.Operations.ServiceSoap>, C_DentalClaimTracker.DCOPlus.Operations.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C_DentalClaimTracker.DCOPlus.Operations.UploadFileResponse C_DentalClaimTracker.DCOPlus.Operations.ServiceSoap.UploadFile(C_DentalClaimTracker.DCOPlus.Operations.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public bool UploadFile(string Key, string Name, byte[] Content) {
            C_DentalClaimTracker.DCOPlus.Operations.UploadFileRequest inValue = new C_DentalClaimTracker.DCOPlus.Operations.UploadFileRequest();
            inValue.Body = new C_DentalClaimTracker.DCOPlus.Operations.UploadFileRequestBody();
            inValue.Body.Key = Key;
            inValue.Body.Name = Name;
            inValue.Body.Content = Content;
            C_DentalClaimTracker.DCOPlus.Operations.UploadFileResponse retVal = ((C_DentalClaimTracker.DCOPlus.Operations.ServiceSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C_DentalClaimTracker.DCOPlus.Operations.UploadContentResponse C_DentalClaimTracker.DCOPlus.Operations.ServiceSoap.UploadContent(C_DentalClaimTracker.DCOPlus.Operations.UploadContentRequest request) {
            return base.Channel.UploadContent(request);
        }
        
        public bool UploadContent(string CBOId, string UserName, string Password, string FileName, string Content) {
            C_DentalClaimTracker.DCOPlus.Operations.UploadContentRequest inValue = new C_DentalClaimTracker.DCOPlus.Operations.UploadContentRequest();
            inValue.Body = new C_DentalClaimTracker.DCOPlus.Operations.UploadContentRequestBody();
            inValue.Body.CBOId = CBOId;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.FileName = FileName;
            inValue.Body.Content = Content;
            C_DentalClaimTracker.DCOPlus.Operations.UploadContentResponse retVal = ((C_DentalClaimTracker.DCOPlus.Operations.ServiceSoap)(this)).UploadContent(inValue);
            return retVal.Body.UploadContentResult;
        }
    }
}
